In [2]:
import numpy as np

In [7]:
a=np.array([])
print(a)
print(type(a))

[]
<class 'numpy.ndarray'>


In [3]:
b=np.array([1,2,3,4])
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
b=np.array(['a','b','c','d'])
print(b)
print(type(b))

['a' 'b' 'c' 'd']
<class 'numpy.ndarray'>


In [14]:
c=np.array([1,2,3,4])
print(c)
print(type(c))

[1 2 3 4]
<class 'numpy.ndarray'>


In [16]:
print("\n Dtype: " , c.dtype)
print("\n Dimension: " , c.ndim)
print("\n size of single item: " , c.itemsize)
print("\n shape of aarray: " , c.shape)
print("\n bytes taken by array: " , c.nbytes)


 Dtype:  int32

 Dimension:  1

 size of items:  4

 shape of aarray:  (4,)

 bytes taken by array:  16


In [11]:
print(np.__version__)

1.18.1


In [20]:
a=np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)
print("\n Dtype: " , a.dtype)
print("\n Dimension: " , a.ndim)
print("\n size of single item: " , a.itemsize)
print("\n shape of aarray: " , a.shape)
print("\n bytes taken by array: " , a.nbytes)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

 Dtype:  int32

 Dimension:  2

 size of single item:  4

 shape of aarray:  (4, 2)

 bytes taken by array:  32


In [22]:
a=np.array([['asf','sdf'],['dhgf','fgs']])

In [23]:
#type casting
zarray= np.zeros((4,6))
print(zarray)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [24]:
zarray= np.ones((4,6))
print(zarray)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [25]:
hj=np.full((4,5),2)
print(hj)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [26]:
hj=np.full((4,5),'a')
print(hj)

[['a' 'a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a' 'a']]


In [28]:
hj=np.full((5,3),7)
print(hj)

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [29]:
zarray= np.zeros((6,7))
print(zarray)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [30]:
zarray= np.ones((3,8))
print(zarray)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
