In [1]:
import numpy as np

# Array functions

In [2]:
#creating 1d array
a1= [21,31,41,51]
narray = np.array(a1)
print(narray)

[21 31 41 51]


In [3]:
type(narray)

numpy.ndarray

In [5]:
#creating 2d array 
b1= [22,33,44,55]
narray2 = np.array([a1,b1])
print (narray2)

[[21 31 41 51]
 [22 33 44 55]]


In [6]:
type(narray2)

numpy.ndarray

In [7]:
#finding dimensions of array- shape
print("Shape of 1d array")
print(narray.shape)

print("shape of 2d array")
print(narray2.shape)

Shape for 1d array
(4,)
shape for 2d array
(2, 4)


In [8]:
#finding data type of array - dtype
print("datatype of 1d array")
print(narray.dtype)

print("datatype of 2d array")
print(narray2.dtype)

datatype of 1d array
int32
datatype of 2d array
int32


In [9]:
# array creation and initialization function - zero
print("1D zero")
zarray= np.zeros(5)
print(zarray)

print("2D array")
zarray2= np.zeros([5,5])
print(zarray2)

1D zero
[0. 0. 0. 0. 0.]
2D array
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
#array creation and initializaton function - ones
print("1D Ones")
oarray= np.ones(5)
print(oarray)

print("2D array")
oarray2= np.ones([5,5])
print(oarray2)

1D Ones
[1. 1. 1. 1. 1.]
2D array
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
#creating and initializing function - empty
print("1D array")
earray= np.empty(4)
print(earray)

print("2D array")
earray2= np.empty([4,4])
print(earray2)

1D array
[6.57818695e-313 1.08221785e-312 7.00258611e-313 1.16709769e-312]
2D array
[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.06811083e-306]
 [8.34441742e-308 1.78022342e-306 6.23058028e-307 9.79107872e-307]
 [6.89807188e-307 7.56594375e-307 6.23060065e-307 1.78021527e-306]
 [8.34454050e-308 1.11261027e-306 1.15706896e-306 1.33512173e-306]]


In [12]:
#array creation and initiallization fuction - eye
iarray = np.eye(5)
print(iarray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
#array creation and initialization function - arrange
aArray= np.arange(0,50,2)  #(ini. value, end value , with the gap of )
print(aArray)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [21]:
#function of numpy array- arange
a3= np.arange(30)
print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [22]:
#function of numpy array- arange()
a4= np.arange(10,30)
print(a4)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [23]:
#function of numpy array- arange
a4= np.arange(0,30,3)
print(a4)

[ 0  3  6  9 12 15 18 21 24 27]


In [24]:
b1= np.sqrt(a4)
print(b1)

[0.         1.73205081 2.44948974 3.         3.46410162 3.87298335
 4.24264069 4.58257569 4.89897949 5.19615242]


In [26]:
#function of numpy array - exp() [exponential function(e to the power of x)value of e=2.718]
a1=np.array([10,21,12,14])
e = np.exp(a1)
print(e)

[2.20264658e+04 1.31881573e+09 1.62754791e+05 1.20260428e+06]


In [35]:
#function of numpy array - random() creates an array of speciffied shape and 
#fills it with random values as per standard normal distribution

f= np.random.randn(6)
print(f)

[-1.90625921  1.38709403  1.23454611  1.00536752  0.07273494 -0.70035006]


In [28]:
f= np.random.randn(5,5)
print(f)

[[ 0.12707445  0.06342984 -1.64823757 -0.11386163 -0.45578141]
 [ 0.25623122 -1.01851543 -0.5642091  -0.98831775 -0.39778976]
 [ 0.30696998  0.30304528 -0.42585403 -0.16073743 -0.23373213]
 [ 0.24331595 -1.01886748  1.06293349  0.03807659  2.36722758]
 [-1.57047465  0.34739582  0.37378868  0.02222965 -1.25075704]]


# Scalar Operation

In [29]:
#function of numpy array - add()

a1= np.array([[1,2,3],[4,5,6]])
a2= np.array([[1,2,3],[4,5,6]])

np.add(a1,a2)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [15]:
#scalar array multiplication - usinig * operation

a1 = np.array([[11,12,13], [21,22,23]])
print(a1)

[[11 12 13]
 [21 22 23]]


In [16]:
type(a1)

numpy.ndarray

In [17]:
b1= a1*a1
print(b1)

[[121 144 169]
 [441 484 529]]


In [18]:
#exponential multiplication- using ** operator
c1= a1**2 #doing the squares
print(c1)

[[121 144 169]
 [441 484 529]]


In [19]:
#scalar substraction of array elements
d1= c1-a1
print(d1)

[[110 132 156]
 [420 462 506]]


In [20]:
#scalar division of array elements
f1= 1/a1
print(f1)

[[0.09090909 0.08333333 0.07692308]
 [0.04761905 0.04545455 0.04347826]]


# accessing elements in array

In [30]:
#accesing individual element in array

a1 = np.arange(0,100,5)
print(a1)

print("Getting first Element")
print(a1[0])

print("getting second element")
print(a1[1])

print("gettting last element")
print(a1[-1])

print("getting second last element")
print(a1[-2])


[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
Getting first Element
0
getting second element
5
gettting last element
95
getting second last element
90


In [31]:
#slicing of array index [start:stop:gap]

print("grabing first 5 elements in a1")
a1[0:6]

grabing first 5 elements in a1


array([ 0,  5, 10, 15, 20, 25])

In [33]:
print("gtrabing first 5 elements in a1 with gap of 1")
a1[0:6:2]

gtrabing first 5 elements in a1 with gap of 1


array([ 0, 10, 20])

In [34]:
#updation of array using slicing 

print("change first 5 elements to 7")
a1[0:6] =7  #changing the numbers
print(a1)

change first 5 elements to 7
[ 7  7  7  7  7  7 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
